### ISSUE TITLE
add repo param-order incorrect in --help

### ISSUE THREAD

**Issue by iambmelt** [clarkda/cocoapods-repo-svn#5]
**Issue:**

Parameter order reported in reverse order for ``pod repo-svn add``

Gem list:

    cocoapods (0.34.2)
    cocoapods-core (0.34.2)
    cocoapods-downloader (0.7.2)
    cocoapods-plugins (0.3.1)
    cocoapods-repo-svn (0.1.1)
    
Gem version:

    2.0.14
    
pod docs: [version 0.34.2 -- correct]

    brianmelton$ pod repo add --help
    Usage:

    $ pod repo add NAME URL [BRANCH]

      Clones `URL` in the local spec-repos directory at `~/.cocoapods/repos/`. The
      remote can later be referred to by `NAME`.

    Options:

    --shallow   Create a shallow clone (fast clone, but no push capabilities)
    --silent    Show nothing
    --verbose   Show more debugging information
    --no-ansi   Show output without ANSI codes
    --help      Show help banner of specified command
    
repo-svn docs: [version 0.1.1 -- incorrect]

    brianmelton$ pod repo-svn add --help
    Usage:

    $ pod repo-svn add URL NAME

      Check out `URL` in the local spec-repos directory at `~/.cocoapods/repos/`. The
      remote can later be referred to by `NAME`.

    Options:

    --silent    Show nothing
    --verbose   Show more debugging information
    --no-ansi   Show output without ANSI codes
    --help      Show help banner of specified command
    
repo-svn docs: [version 0.1.0 -- correct]

    brianmelton$ pod repo-svn add --help
    Usage:

    $ pod repo-svn add NAME URL

      Check out `URL` in the local spec-repos directory at `~/.cocoapods/repos/`. The
      remote can later be referred to by `NAME`.

    Options:

    --silent    Show nothing
    --verbose   Show more debugging information
    --no-ansi   Show output without ANSI codes
    --help      Show help banner of specified command

**Comment by clarkda** [comment]
Doh! Fixed in 82c3540

Thanks for the bug report! Let me know if you have anymore issues.
