### ISSUE TITLE
I do add repo-svn command,but nothing happend

### ISSUE THREAD

**Issue by xiaozi4624** [clarkda/cocoapods-repo-svn#6]
![f6281f6a-1961-41af-bc02-37067ade1dea](https://cloud.githubusercontent.com/assets/3972317/7134737/54853dfc-e2d2-11e4-8152-c04682e8bfda.png)
![ee503807-7e86-4f74-b478-3cdec1946b74](https://cloud.githubusercontent.com/assets/3972317/7134736/548500b2-e2d2-11e4-9d2f-9ca5daca5342.png)

**Comment by xiaozi4624** [comment]
![74ca448c-2ba0-45ea-b8a4-41ed5b8d02a5](https://cloud.githubusercontent.com/assets/3972317/7156824/5ef185e6-e39c-11e4-882a-a4703eefcc55.png)

@clarkda

**Comment by clarkda** [comment]
Hey @xiaozi4624 thanks for the bug report, could you pod --version and let me know what version of cocoapods you are using?

**Comment by xiaozi4624** [comment]
The version is 0.36.3

**Comment by clarkda** [comment]
@xiaozi4624 i've found a issue in cocoapods core and i'm working on a patch. going to try to finish the unit tests this weekend and hopefully it'll be a little easier to see breaks between new versions of cocoapods

**Comment by xiaozi4624** [comment]
Thanks for the work!

**Comment by TimeSkyBlack** [comment]
![qq20150810-1](https://cloud.githubusercontent.com/assets/5791830/9160402/e55e61dc-3f6b-11e5-8d75-89d910b8b3f7.png)
![qq20150810-2](https://cloud.githubusercontent.com/assets/5791830/9160403/e58c278e-3f6b-11e5-8ff2-ac070057d762.png)

my pods version is 0.38.2 and i also found the issue,is my usage wrong?

**Comment by clarkda** [comment]
@TimeSkyBlack I've just released a new version of the plugin at `2.0.0` .. you'll need this + the very latest from `master` for `https://github.com/cocoapods/cocoapods`

Having done that your `Podfile` will end up looking something like

```
chunk:test-svn-project dusty$ cat Podfile
plugin 'cocoapods-repo-svn', :sources => [
  'http://192.168.99.100/svn/repo/master-svn/'
]

pod 'LoL-svn'
```

**Comment by clarkda** [comment]
you'll have to use `master` until `cocoapods` does a release that includes @amorde's changes :cake: 

i'm sure that will happen very soon? :pray:

**Comment by TimeSkyBlack** [comment]
@clarkda yeah!!! i build the latest cocoapods and 2.0.0  ,and it work as usual~！！！thanks a lot😊

**Comment by clarkda** [comment]
@TimeSkyBlack awesome! sorry for the crazy delay!

**Comment by amorde** [comment]
@TimeSkyBlack glad to hear it's working for you! :)
