### ISSUE TITLE
"Unable to find specification .." during pod install, but "pod spec which" succeeds

### ISSUE THREAD

**Issue by amorde** [clarkda/cocoapods-repo-svn#7]
I might be doing this incorrectly, but I have added my repo successfully using `pod repo-svn add` and tested to see if cocoapods recognizes the template by running `pod spec which MyPod`

    /Users/eric.amorde/.cocoapods/repos/private/Specs/MyPod/1.0.0/MyPod.podspec

But when trying a `pod install` on a project in which the Podfile declares `MyPod` as a dependency yields:

    $ pod install
    Analyzing dependencies
    [!] Unable to find a specification for `MyPod`

The only thing I can think of is that at the top of the Podfile, I cannot add my repo as a `source` because cocoapods does not recognize that it is not a git repo and will fail.

**Comment by clarkda** [comment]
Hey @amorde! What `version` of `cocoapods` are you using?

**Comment by amorde** [comment]
I was using 0.36 at the time, but have also used 0.37 and am now using 0.38.0.beta to test the new plugin api described [here](https://github.com/CocoaPods/CocoaPods/pull/3540)

I have a version of your plugin on my machine that supports the `plugin 'cocoapods-repo-svn'` syntax. If you're interested, I could clean it up and submit a PR. I was planning on making my own plugin that supports using local spec repos as sources in a Podfile

**Comment by clarkda** [comment]
@amorde I *really* like the changes proposed in https://github.com/CocoaPods/CocoaPods/pull/3792

And I always appreciate PRs!

**Comment by amorde** [comment]
Glad to hear it! If that PR makes it through, I'd be more than happy to implement it in this plugin and submit a PR

**Comment by amorde** [comment]
This issue likely isn't relevant anymore since it has to do with CocoaPods itself, so I'll close it.
